applicationURL: "https://www.securian.com/insights-tools/retirement-calculator.html"
browser: "chrome"
currentAge: "40"
RetirementAge: "68"
CurrentAnnualIncome: "100000"
SpouseAnnualIncome: "75000"
CurrentRetirementSavings: "500000"
CurrentRetirementContribution: "10"
AnnualIncomeRetirementContribution: "2"
SocialSecurityIncome: "Yes"
RelationshipStatus: "Married"
AdditionalIncome: "500"
NumberOfYearsRetirement: "20"
PostRetirementIncomeIncrease: "Yes"
PercentOfFinalAnnualIncome: "75"
PreRetirementInvestmentReturn: "8"
PostRetirementInvestmentReturn: "5"
